<?php $current_user_id = get_current_user_id();
$current_country = get_user_meta($current_user_id, 'country_region', true); ?>

<option value="">Country/Region</option>
<option <?php selected($current_country, "Afghanistan") ?> value="Afghanistan">Afghanistan</option>
<option <?php selected($current_country, "Åland Islands") ?> value="Åland Islands">Åland Islands</option>
<option <?php selected($current_country, "Albania") ?> value="Albania">Albania</option>
<option <?php selected($current_country, "Algeria") ?> value="Algeria">Algeria</option>
<option <?php selected($current_country, "American Samoa") ?> value="American Samoa">American Samoa</option>
<option <?php selected($current_country, "Andorra") ?> value="Andorra">Andorra</option>
<option <?php selected($current_country, "Angola") ?> value="Angola">Angola</option>
<option <?php selected($current_country, "Anguilla") ?> value="Anguilla">Anguilla</option>
<option <?php selected($current_country, "Antarctica") ?> value="Antarctica">Antarctica</option>
<option <?php selected($current_country, "Antigua and Barbuda") ?> value="Antigua and Barbuda">Antigua and Barbuda</option>
<option <?php selected($current_country, "Argentina") ?> value="Argentina">Argentina</option>
<option <?php selected($current_country, "Armenia") ?> value="Armenia">Armenia</option>
<option <?php selected($current_country, "Aruba") ?> value="Aruba">Aruba</option>
<option <?php selected($current_country, "Australia") ?> value="Australia">Australia</option>
<option <?php selected($current_country, "Austria") ?> value="Austria">Austria</option>
<option <?php selected($current_country, "Azerbaijan") ?> value="Azerbaijan">Azerbaijan</option>
<option <?php selected($current_country, "Bahamas") ?> value="Bahamas">Bahamas</option>
<option <?php selected($current_country, "Bahrain") ?> value="Bahrain">Bahrain</option>
<option <?php selected($current_country, "Bangladesh") ?> value="Bangladesh">Bangladesh</option>
<option <?php selected($current_country, "Barbados") ?> value="Barbados">Barbados</option>
<option <?php selected($current_country, "Belarus") ?> value="Belarus">Belarus</option>
<option <?php selected($current_country, "Belgium") ?> value="Belgium">Belgium</option>
<option <?php selected($current_country, "Belize") ?> value="Belize">Belize</option>
<option <?php selected($current_country, "Benin") ?> value="Benin">Benin</option>
<option <?php selected($current_country, "Bermuda") ?> value="Bermuda">Bermuda</option>
<option <?php selected($current_country, "Bhutan") ?> value="Bhutan">Bhutan</option>
<option <?php selected($current_country, "Bolivia") ?> value="Bolivia">Bolivia</option>
<option <?php selected($current_country, "Bosnia and Herzegovina") ?> value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
<option <?php selected($current_country, "Botswana") ?> value="Botswana">Botswana</option>
<option <?php selected($current_country, "Bouvet Island") ?> value="Bouvet Island">Bouvet Island</option>
<option <?php selected($current_country, "Brazil") ?> value="Brazil">Brazil</option>
<option <?php selected($current_country, "British Indian Ocean Territory") ?> value="British Indian Ocean Territory">British Indian Ocean Territory</option>
<option <?php selected($current_country, "Brunei Darussalam") ?> value="Brunei Darussalam">Brunei Darussalam</option>
<option <?php selected($current_country, "Bulgaria") ?> value="Bulgaria">Bulgaria</option>
<option <?php selected($current_country, "Burkina Faso") ?> value="Burkina Faso">Burkina Faso</option>
<option <?php selected($current_country, "Burundi") ?> value="Burundi">Burundi</option>
<option <?php selected($current_country, "Cambodia") ?> value="Cambodia">Cambodia</option>
<option <?php selected($current_country, "Cameroon") ?> value="Cameroon">Cameroon</option>
<option <?php selected($current_country, "Canada") ?> value="Canada">Canada</option>
<option <?php selected($current_country, "Cape") ?> value="Cape Verde">Cape Verde</option>
<option <?php selected($current_country, "Cayman Islands") ?> value="Cayman Islands">Cayman Islands</option>
<option <?php selected($current_country, "Central African Republic") ?> value="Central African Republic">Central African Republic</option>
<option <?php selected($current_country, "Chad") ?> value="Chad">Chad</option>
<option <?php selected($current_country, "Chile") ?> value="Chile">Chile</option>
<option <?php selected($current_country, "China") ?> value="China">China</option>
<option <?php selected($current_country, "Christmas Island") ?> value="Christmas Island">Christmas Island</option>
<option <?php selected($current_country, "Cocos (Keeling) Islands") ?> value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
<option <?php selected($current_country, "Colombia") ?> value="Colombia">Colombia</option>
<option <?php selected($current_country, "Comoros") ?> value="Comoros">Comoros</option>
<option <?php selected($current_country, "Congo") ?> value="Congo">Congo</option>
<option <?php selected($current_country, "Congo, The Democratic Republic of The") ?> value="Congo, The Democratic Republic of The">Congo, The Democratic Republic of The</option>
<option <?php selected($current_country, "Cook Islands") ?> value="Cook Islands">Cook Islands</option>
<option <?php selected($current_country, "Costa Rica") ?> value="Costa Rica">Costa Rica</option>
<option <?php selected($current_country, "Cote D'ivoire") ?> value="Cote D'ivoire">Cote D'ivoire</option>
<option <?php selected($current_country, "Croatia") ?> value="Croatia">Croatia</option>
<option <?php selected($current_country, "Cuba") ?> value="Cuba">Cuba</option>
<option <?php selected($current_country, "Cyprus") ?> value="Cyprus">Cyprus</option>
<option <?php selected($current_country, "Czech Republic") ?> value="Czech Republic">Czech Republic</option>
<option <?php selected($current_country, "Denmark") ?> value="Denmark">Denmark</option>
<option <?php selected($current_country, "Djibouti") ?> value="Djibouti">Djibouti</option>
<option <?php selected($current_country, "Dominica") ?> value="Dominica">Dominica</option>
<option <?php selected($current_country, "Dominican Republic") ?> value="Dominican Republic">Dominican Republic</option>
<option <?php selected($current_country, "Ecuador") ?> value="Ecuador">Ecuador</option>
<option <?php selected($current_country, "Egypt") ?> value="Egypt">Egypt</option>
<option <?php selected($current_country, "El Salvador") ?> value="El Salvador">El Salvador</option>
<option <?php selected($current_country, "Equatorial Guinea") ?> value="Equatorial Guinea">Equatorial Guinea</option>
<option <?php selected($current_country, "Eritrea") ?> value="Eritrea">Eritrea</option>
<option <?php selected($current_country, "Estonia") ?> value="Estonia">Estonia</option>
<option <?php selected($current_country, "Ethiopia") ?> value="Ethiopia">Ethiopia</option>
<option <?php selected($current_country, "Falkland Islands (Malvinas)") ?> value="Falkland Islands (Malvinas)">Falkland Islands (Malvinas)</option>
<option <?php selected($current_country, "Faroe Islands") ?> value="Faroe Islands">Faroe Islands</option>
<option <?php selected($current_country, "Fiji") ?> value="Fiji">Fiji</option>
<option <?php selected($current_country, "Finland") ?> value="Finland">Finland</option>
<option <?php selected($current_country, "France") ?> value="France">France</option>
<option <?php selected($current_country, "French Guiana") ?> value="French Guiana">French Guiana</option>
<option <?php selected($current_country, "French Polynesia") ?> value="French Polynesia">French Polynesia</option>
<option <?php selected($current_country, "French Southern Territories") ?> value="French Southern Territories">French Southern Territories</option>
<option <?php selected($current_country, "Gabon") ?> value="Gabon">Gabon</option>
<option <?php selected($current_country, "Gambia") ?> value="Gambia">Gambia</option>
<option <?php selected($current_country, "Georgia") ?> value="Georgia">Georgia</option>
<option <?php selected($current_country, "Germany") ?> value="Germany">Germany</option>
<option <?php selected($current_country, "Ghana") ?> value="Ghana">Ghana</option>
<option <?php selected($current_country, "Gibraltar") ?> value="Gibraltar">Gibraltar</option>
<option <?php selected($current_country, "Greece") ?> value="Greece">Greece</option>
<option <?php selected($current_country, "Greenland") ?> value="Greenland">Greenland</option>
<option <?php selected($current_country, "Grenada") ?> value="Grenada">Grenada</option>
<option <?php selected($current_country, "Guadeloupe") ?> value="Guadeloupe">Guadeloupe</option>
<option <?php selected($current_country, "Guam") ?> value="Guam">Guam</option>
<option <?php selected($current_country, "Guatemala") ?> value="Guatemala">Guatemala</option>
<option <?php selected($current_country, "Guernsey") ?> value="Guernsey">Guernsey</option>
<option <?php selected($current_country, "Guinea") ?> value="Guinea">Guinea</option>
<option <?php selected($current_country, "Guinea-bissau") ?> value="Guinea-bissau">Guinea-bissau</option>
<option <?php selected($current_country, "Guyana") ?> value="Guyana">Guyana</option>
<option <?php selected($current_country, "Haiti") ?> value="Haiti">Haiti</option>
<option <?php selected($current_country, "Heard Island and Mcdonald Islands") ?> value="Heard Island and Mcdonald Islands">Heard Island and Mcdonald Islands</option>
<option <?php selected($current_country, "Holy See (Vatican City State)") ?> value="Holy See (Vatican City State)">Holy See (Vatican City State)</option>
<option <?php selected($current_country, "Honduras") ?> value="Honduras">Honduras</option>
<option <?php selected($current_country, "Hong Kong") ?> value="Hong Kong">Hong Kong</option>
<option <?php selected($current_country, "Hungary") ?> value="Hungary">Hungary</option>
<option <?php selected($current_country, "Iceland") ?> value="Iceland">Iceland</option>
<option <?php selected($current_country, "India") ?> value="India">India</option>
<option <?php selected($current_country, "Indonesia") ?> value="Indonesia">Indonesia</option>
<option <?php selected($current_country, "Iran, Islamic Republic of") ?> value="Iran, Islamic Republic of">Iran, Islamic Republic of</option>
<option <?php selected($current_country, "Iraq") ?> value="Iraq">Iraq</option>
<option <?php selected($current_country, "Ireland") ?> value="Ireland">Ireland</option>
<option <?php selected($current_country, "Isle of Man") ?> value="Isle of Man">Isle of Man</option>
<option <?php selected($current_country, "Israel") ?> value="Israel">Israel</option>
<option <?php selected($current_country, "Italy") ?> value="Italy">Italy</option>
<option <?php selected($current_country, "Jamaica") ?> value="Jamaica">Jamaica</option>
<option <?php selected($current_country, "Japan") ?> value="Japan">Japan</option>
<option <?php selected($current_country, "Jersey") ?> value="Jersey">Jersey</option>
<option <?php selected($current_country, "Jordan") ?> value="Jordan">Jordan</option>
<option <?php selected($current_country, "Kazakhstan") ?> value="Kazakhstan">Kazakhstan</option>
<option <?php selected($current_country, "Kenya") ?> value="Kenya">Kenya</option>
<option <?php selected($current_country, "Kiribati") ?> value="Kiribati">Kiribati</option>
<option <?php selected($current_country, "Korea, Democratic People's Republic of") ?> value="Korea, Democratic People's Republic of">Korea, Democratic People's Republic of</option>
<option <?php selected($current_country, "Korea, Republic of") ?> value="Korea, Republic of">Korea, Republic of</option>
<option <?php selected($current_country, "Kuwait") ?> value="Kuwait">Kuwait</option>
<option <?php selected($current_country, "Kyrgyzstan") ?> value="Kyrgyzstan">Kyrgyzstan</option>
<option <?php selected($current_country, "Lao People's Democratic Republic") ?> value="Lao People's Democratic Republic">Lao People's Democratic Republic</option>
<option <?php selected($current_country, "Latvia") ?> value="Latvia">Latvia</option>
<option <?php selected($current_country, "Lebanon") ?> value="Lebanon">Lebanon</option>
<option <?php selected($current_country, "Lesotho") ?> value="Lesotho">Lesotho</option>
<option <?php selected($current_country, "Liberia") ?> value="Liberia">Liberia</option>
<option <?php selected($current_country, "Libyan Arab Jamahiriya") ?> value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
<option <?php selected($current_country, "Liechtenstein") ?> value="Liechtenstein">Liechtenstein</option>
<option <?php selected($current_country, "Lithuania") ?> value="Lithuania">Lithuania</option>
<option <?php selected($current_country, "Luxembourg") ?> value="Luxembourg">Luxembourg</option>
<option <?php selected($current_country, "Macao") ?> value="Macao">Macao</option>
<option <?php selected($current_country, "Macedonia, The Former Yugoslav Republic of") ?> value="Macedonia, The Former Yugoslav Republic of">Macedonia, The Former Yugoslav Republic of</option>
<option <?php selected($current_country, "Madagascar") ?> value="Madagascar">Madagascar</option>
<option <?php selected($current_country, "Malawi") ?> value="Malawi">Malawi</option>
<option <?php selected($current_country, "Malaysia") ?> value="Malaysia">Malaysia</option>
<option <?php selected($current_country, "Maldives") ?> value="Maldives">Maldives</option>
<option <?php selected($current_country, "Mali") ?> value="Mali">Mali</option>
<option <?php selected($current_country, "Malta") ?> value="Malta">Malta</option>
<option <?php selected($current_country, "Marshall Islands") ?> value="Marshall Islands">Marshall Islands</option>
<option <?php selected($current_country, "Martinique") ?> value="Martinique">Martinique</option>
<option <?php selected($current_country, "Mauritania") ?> value="Mauritania">Mauritania</option>
<option <?php selected($current_country, "Mauritius") ?> value="Mauritius">Mauritius</option>
<option <?php selected($current_country, "Mayotte") ?> value="Mayotte">Mayotte</option>
<option <?php selected($current_country, "Mexico") ?> value="Mexico">Mexico</option>
<option <?php selected($current_country, "Micronesia, Federated States of") ?> value="Micronesia, Federated States of">Micronesia, Federated States of</option>
<option <?php selected($current_country, "Moldova, Republic of") ?> value="Moldova, Republic of">Moldova, Republic of</option>
<option <?php selected($current_country, "Monaco") ?> value="Monaco">Monaco</option>
<option <?php selected($current_country, "Mongolia") ?> value="Mongolia">Mongolia</option>
<option <?php selected($current_country, "Montenegro") ?> value="Montenegro">Montenegro</option>
<option <?php selected($current_country, "Montserrat") ?> value="Montserrat">Montserrat</option>
<option <?php selected($current_country, "Morocco") ?> value="Morocco">Morocco</option>
<option <?php selected($current_country, "Mozambique") ?> value="Mozambique">Mozambique</option>
<option <?php selected($current_country, "Myanmar") ?> value="Myanmar">Myanmar</option>
<option <?php selected($current_country, "Namibia") ?> value="Namibia">Namibia</option>
<option <?php selected($current_country, "Nauru") ?> value="Nauru">Nauru</option>
<option <?php selected($current_country, "Nepal") ?> value="Nepal">Nepal</option>
<option <?php selected($current_country, "Netherlands") ?> value="Netherlands">Netherlands</option>
<option <?php selected($current_country, "Netherlands Antilles") ?> value="Netherlands Antilles">Netherlands Antilles</option>
<option <?php selected($current_country, "New Caledonia") ?> value="New Caledonia">New Caledonia</option>
<option <?php selected($current_country, "New Zealand") ?> value="New Zealand">New Zealand</option>
<option <?php selected($current_country, "Nicaragua") ?> value="Nicaragua">Nicaragua</option>
<option <?php selected($current_country, "Niger") ?> value="Niger">Niger</option>
<option <?php selected($current_country, "Nigeria") ?> value="Nigeria">Nigeria</option>
<option <?php selected($current_country, "Niue") ?> value="Niue">Niue</option>
<option <?php selected($current_country, "Norfolk Island") ?> value="Norfolk Island">Norfolk Island</option>
<option <?php selected($current_country, "Northern Mariana Islands") ?> value="Northern Mariana Islands">Northern Mariana Islands</option>
<option <?php selected($current_country, "Norway") ?> value="Norway">Norway</option>
<option <?php selected($current_country, "Oman") ?> value="Oman">Oman</option>
<option <?php selected($current_country, "Pakistan") ?> value="Pakistan">Pakistan</option>
<option <?php selected($current_country, "Palau") ?> value="Palau">Palau</option>
<option <?php selected($current_country, "Palestinian Territory, Occupied") ?> value="Palestinian Territory, Occupied">Palestinian Territory, Occupied</option>
<option <?php selected($current_country, "Panama") ?> value="Panama">Panama</option>
<option <?php selected($current_country, "Papua New Guinea") ?> value="Papua New Guinea">Papua New Guinea</option>
<option <?php selected($current_country, "Paraguay") ?> value="Paraguay">Paraguay</option>
<option <?php selected($current_country, "Peru") ?> value="Peru">Peru</option>
<option <?php selected($current_country, "Philippines") ?> value="Philippines">Philippines</option>
<option <?php selected($current_country, "Pitcairn") ?> value="Pitcairn">Pitcairn</option>
<option <?php selected($current_country, "Poland") ?> value="Poland">Poland</option>
<option <?php selected($current_country, "Portugal") ?> value="Portugal">Portugal</option>
<option <?php selected($current_country, "Puerto Rico") ?> value="Puerto Rico">Puerto Rico</option>
<option <?php selected($current_country, "Qatar") ?> value="Qatar">Qatar</option>
<option <?php selected($current_country, "Reunion") ?> value="Reunion">Reunion</option>
<option <?php selected($current_country, "Romania") ?> value="Romania">Romania</option>
<option <?php selected($current_country, "Russian Federation") ?> value="Russian Federation">Russian Federation</option>
<option <?php selected($current_country, "Rwanda") ?> value="Rwanda">Rwanda</option>
<option <?php selected($current_country, "Saint Helena") ?> value="Saint Helena">Saint Helena</option>
<option <?php selected($current_country, "Saint Kitts and Nevis") ?> value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
<option <?php selected($current_country, "Saint Lucia") ?> value="Saint Lucia">Saint Lucia</option>
<option <?php selected($current_country, "Saint Pierre and Miquelon") ?> value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
<option <?php selected($current_country, "Saint Vincent and The Grenadines") ?> value="Saint Vincent and The Grenadines">Saint Vincent and The Grenadines</option>
<option <?php selected($current_country, "Samoa") ?> value="Samoa">Samoa</option>
<option <?php selected($current_country, "San Marino") ?> value="San Marino">San Marino</option>
<option <?php selected($current_country, "Sao Tome and Principe") ?> value="Sao Tome and Principe">Sao Tome and Principe</option>
<option <?php selected($current_country, "Saudi Arabia") ?> value="Saudi Arabia">Saudi Arabia</option>
<option <?php selected($current_country, "Senegal") ?> value="Senegal">Senegal</option>
<option <?php selected($current_country, "Serbia") ?> value="Serbia">Serbia</option>
<option <?php selected($current_country, "Seychelles") ?> value="Seychelles">Seychelles</option>
<option <?php selected($current_country, "Sierra Leone") ?> value="Sierra Leone">Sierra Leone</option>
<option <?php selected($current_country, "Singapore") ?> value="Singapore">Singapore</option>
<option <?php selected($current_country, "Slovakia") ?> value="Slovakia">Slovakia</option>
<option <?php selected($current_country, "Slovenia") ?> value="Slovenia">Slovenia</option>
<option <?php selected($current_country, "Solomon Islands") ?> value="Solomon Islands">Solomon Islands</option>
<option <?php selected($current_country, "Somalia") ?> value="Somalia">Somalia</option>
<option <?php selected($current_country, "South") ?> value="South Africa">South Africa</option>
<option <?php selected($current_country, "South Georgia and The South Sandwich Islands") ?> value="South Georgia and The South Sandwich Islands">South Georgia and The South Sandwich Islands</option>
<option <?php selected($current_country, "Spain") ?> value="Spain">Spain</option>
<option <?php selected($current_country, "Sri Lanka") ?> value="Sri Lanka">Sri Lanka</option>
<option <?php selected($current_country, "Sudan") ?> value="Sudan">Sudan</option>
<option <?php selected($current_country, "Suriname") ?> value="Suriname">Suriname</option>
<option <?php selected($current_country, "Svalbard and Jan Mayen") ?> value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
<option <?php selected($current_country, "Swaziland") ?> value="Swaziland">Swaziland</option>
<option <?php selected($current_country, "Sweden") ?> value="Sweden">Sweden</option>
<option <?php selected($current_country, "Switzerland") ?> value="Switzerland">Switzerland</option>
<option <?php selected($current_country, "Syrian Arab Republic") ?> value="Syrian Arab Republic">Syrian Arab Republic</option>
<option <?php selected($current_country, "Taiwan") ?> value="Taiwan">Taiwan</option>
<option <?php selected($current_country, "Tajikistan") ?> value="Tajikistan">Tajikistan</option>
<option <?php selected($current_country, "Tanzania, United Republic of") ?> value="Tanzania, United Republic of">Tanzania, United Republic of</option>
<option <?php selected($current_country, "Thailand") ?> value="Thailand">Thailand</option>
<option <?php selected($current_country, "Timor-leste") ?> value="Timor-leste">Timor-leste</option>
<option <?php selected($current_country, "Togo") ?> value="Togo">Togo</option>
<option <?php selected($current_country, "Tokelau") ?> value="Tokelau">Tokelau</option>
<option <?php selected($current_country, "Tonga") ?> value="Tonga">Tonga</option>
<option <?php selected($current_country, "Trinidad and Tobago") ?> value="Trinidad and Tobago">Trinidad and Tobago</option>
<option <?php selected($current_country, "Tunisia") ?> value="Tunisia">Tunisia</option>
<option <?php selected($current_country, "Turkey") ?> value="Turkey">Turkey</option>
<option <?php selected($current_country, "Turkmenistan") ?> value="Turkmenistan">Turkmenistan</option>
<option <?php selected($current_country, "Turks and Caicos Islands") ?> value="Turks and Caicos Islands">Turks and Caicos Islands</option>
<option <?php selected($current_country, "Tuvalu") ?> value="Tuvalu">Tuvalu</option>
<option <?php selected($current_country, "Uganda") ?> value="Uganda">Uganda</option>
<option <?php selected($current_country, "Ukraine") ?> value="Ukraine">Ukraine</option>
<option <?php selected($current_country, "United Arab Emirates") ?> value="United Arab Emirates">United Arab Emirates</option>
<option <?php selected($current_country, "United Kingdom") ?> value="United Kingdom">United Kingdom</option>
<option <?php selected($current_country, "United States") ?> value="United States">United States</option>
<option <?php selected($current_country, "United States Minor Outlying Islands") ?> value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
<option <?php selected($current_country, "Uruguay") ?> value="Uruguay">Uruguay</option>
<option <?php selected($current_country, "Uzbekistan") ?> value="Uzbekistan">Uzbekistan</option>
<option <?php selected($current_country, "Vanuatu") ?> value="Vanuatu">Vanuatu</option>
<option <?php selected($current_country, "Venezuela") ?> value="Venezuela">Venezuela</option>
<option <?php selected($current_country, "Viet Nam") ?> value="Viet Nam">Viet Nam</option>
<option <?php selected($current_country, "Virgin Islands, British") ?> value="Virgin Islands, British">Virgin Islands, British</option>
<option <?php selected($current_country, "Virgin Islands, U.S.") ?> value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
<option <?php selected($current_country, "Wallis and Futuna") ?> value="Wallis and Futuna">Wallis and Futuna</option>
<option <?php selected($current_country, "Western Sahara") ?> value="Western Sahara">Western Sahara</option>
<option <?php selected($current_country, "Yemen") ?> value="Yemen">Yemen</option>
<option <?php selected($current_country, "Zambia") ?> value="Zambia">Zambia</option>
<option <?php selected($current_country, "Zimbabwe") ?> value="Zimbabwe">Zimbabwe</option>